[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=25.1.0",
    "aiomysql>=0.3.2",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "langchain>=1.4.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.2",
    "langchain-mcp-adapters>=0.3.2",
    "langchain-openai>=1.6.2",
    "langgraph>=1.2.11",
    "langgraph-checkpoint-sqlite>=3.1.1",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.52",
    "sqlalchemy-crud-plus>=1.13.3",
    "tiktoken>=0.14.0",
    "uvicorn>=0.52.4",
]
